---
title: "Week 2"
author: "Austin L. Bistline"
date: "September 8, 2018"
output: html_document
---

```{r}
data(iris); library(ggplot2)
names(iris)
```


```{r}
table(iris$Species)
```


```{r}
inTrain = createDataPartition(y=iris$Species, p=0.7, list=FALSE)
training = iris[inTrain, ]
testing = iris[-inTrain, ]
dim(training); dim(testing)
```

```{r}
qplot(Petal.Length, Sepal.Width, colour=Species, data=training)
```

```{r}
library(caret)
modFit = train(Species ~ ., method="rpart", data=training)
print(modFit$finalModel)
```

```{r}
plot(modFit$finalModel, uniform=TRUE, main="Classification Tree")
text(modFit$finalModel, use.n=TRUE, all=TRUE, cex=.8)
```

```{r}
library(rattle)
fancyRpartPlot(modFit$finalModel)
```

```{r}
predict(modFit, newdata=testing)
```

```{r}
library(ElemStatLearn); data(ozone, package="ElemStatLearn")
ozone = ozone[order(ozone$ozone), ]
head(ozone)
```

```{r}
ll = matrix(NA, nrow=10, ncol=155)
for(i in 1:10){
  ss = sample(1:dim(ozone)[1], replace=T)
  ozone0 = ozone[ss, ]; ozone0 = ozone0[order(ozone0$ozone), ]
  loess0 = loess(temperature ~ ozone, data=ozone0, span=0.2)
  ll[i, ] = predict(loess0, newdata=data.frame(ozone=1:155))
}
```

```{r}
ozone0[5:10, ]
```

```{r}
plot(ozone$ozone, ozone$temperature, pch=19, cex=0.5)
for(i in 1:10){lines(1:155, ll[i, ], col="grey", lwd=2)}
lines(1:155, apply(ll, 2, mean), col="red", lwd=2)
```

```{r}
predictors = data.frame(ozone=ozone$ozone)
temperature = ozone$temperature
treebag = bag(predictors, temperature, B=10, bagControl=bagControl(fit=ctreeBag$fit, predict=ctreeBag$pred, aggregate=ctreeBag$aggregate))
```

```{r}
plot(ozone$ozone, temperature, col='lightgrey', pch=19)
points(ozone$ozone, predict(treebag$fits[[1]]$fit, predictors), pch=19, col="red")
points(ozone$ozone, predict(treebag, predictors), pch=19, col="blue")
```

```{r}
ctreeBag$fit
```

```{r}
ctreeBag$pred
```

```{r}
ctreeBag$aggregate
```

```{r}
data(iris); library(ggplot2)
inTrain = createDataPartition(y=iris$Species, p=0.7, list=FALSE)
training = iris[inTrain, ]
testing = iris[-inTrain, ]
```

```{r}
library(caret)
modFit = train(Species ~ ., data=training, method="rf", prox=TRUE)
modFit
```

```{r}
library(randomForest)
getTree(modFit$finalModel, k=2)
```

```{r}
irisP = classCenter(training[, c(3, 4)], training$Species, modFit$finalModel$prox)
irisP = as.data.frame(irisP); irisP$Species = rownames(irisP)
p = qplot(Petal.Width, Petal.Length, col=Species, data=training)
p + geom_point(aes(x=Petal.Width, y=Petal.Length, col=Species),size=5, shape=4, data=irisP)
```

```{r}
pred = predict(modFit, testing); testing$predRight = pred==testing$Species
table(pred, testing$Species)
```

```{r}
# Looking at which 4 we missed
qplot(Petal.Width, Petal.Length, colour=predRight, data=testing, main="newdata Predictions")
```

```{r}
library(ISLR); data(Wage); library(ggplot2); library(caret);
Wage = subset(Wage, select=-c(logwage))
inTrain = createDataPartition(y=Wage$wage, p=0.7, list=FALSE)
training = Wage[inTrain, ]
testing = Wage[-inTrain, ]
```

```{r}
#library(gbm)
modFit = train(wage ~ ., method="gbm", data=training, verbose=FALSE)
print(modFit)
```

```{r}
qplot(predict(modFit, testing), wage, data=testing)
```

```{r}
inTrain = createDataPartition(y=iris$Species, p=0.7, list=FALSE)
training = iris[inTrain, ]
testing = iris[-inTrain, ]
dim(training); dim(testing)
```

```{r}
modlda = train(Species ~ ., data=training, method="lda")
modnb = train(Species ~ ., data = training, method="nb")
plda = predict(modlda, testing); pnb = predict(modnb, testing)
table(plda, pnb)
```

```{r}
equalPredictions = (plda==pnb)
qplot(Petal.Width, Sepal.Width, colour=equalPredictions, data=testing)
```

